development:
  api_key: 278518abb833e6c04e0729af4c449816
  secret_key: fbc373179492ae09806b25fe9fa34765
  canvas_page_name: diputadovirtual
  callback_url: http://diputado.local/
  pretty_errors: true
  set_asset_host_to_callback_url: false
  tunnel:
    public_host_username:
    public_host:
    public_port: 4007
    local_port: 3000
    server_alive_interval: 0
    
production:
  api_key: 278518abb833e6c04e0729af4c449816
  secret_key: fbc373179492ae09806b25fe9fa34765
  canvas_page_name: diputadovirtual
  callback_url: http://diputadovirtual.heroku.com/
  pretty_errors: true
  set_asset_host_to_callback_url: false
  tunnel:
    public_host_username:
    public_host:
    public_port: 4007
    local_port: 3000
    server_alive_interval: 0